name: gurps_ritual_path_magic_model
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: jeff <email@example.com>

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2
  test_coverage: ^0.2.0

dependencies:
  gurps_dart:
    path: ../gurps_dart

dependency_overrides:

environment:
  sdk: ">=2.1.0 <3.0.0"
