name: gurps_rpm_model
description: A starting point for Dart libraries or applications.
version: 0.8.0
# homepage: https://www.example.com
# author: jeff <email@example.com>

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  collection: ^1.14.13
  quiver: ^2.1.3
  gurps_dice:
    version: ^1.1.0
    git:
      url: https://github.com/mjeffw/gurps_dice.git
  gurps_dart:
    version: ^1.4.0
    git:
      url: https://github.com/mjeffw/gurps_dart

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  test_coverage: ^0.4.3
